日程管理系统/calendarSystem/urls.py
from django.urls import path, re_path, include, reverse_lazy

from django.contrib.auth import views as auth_views
from . import views

app_name = 'calendarSystem'
urlpatterns = [
    
    path('', views.calendar_view, name='calendar'),
    # path("", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path('statistic/<str:mydate>/', views.statistic, name='statistic'),
    
    path('event/new/<str:mydate>/', views.event, name='event_new'),

	re_path('event/edit/(?P<event_id>\d+)/', views.editevent, name='event_edit'),
    re_path("event/update/(?P<event_id>\d+)", views.updateevent, name = 'event_update'),
    
    re_path('event/delete/(?P<event_id>\d+)/', views.delete, name='event_delete'),
    path("user_info/", views.user_info),

]

日程管理系统/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cal/", include("calendarSystem.urls")),
    path("", include("users.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # untuk save gambar

日程管理系统/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("", views.dashboard, name='dashboard'),   
    path("about/", views.about, name="about"),
    path("changepass/", views.changepass, name="change"),
    path("subscription/", views.subscription, name="subscription"),
    path("login/", views.LoginPage, name="login"),
    path("signup/", views.SignupPage, name="signup"),
    path("signup_admin/", views.SignupAdmin, name="signupadmin"),
    path('profile/', views.profile, name='profile'),
    path("logout/", views.LogoutPage, name="logout"),
]

日程管理系统/calendarSystem/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Event(models.Model):
    event_id = models.AutoField(primary_key = True)
    title = models.CharField(max_length = 200)
    description = models.TextField()
    start_time = models.DateTimeField()
    # end_time = models.DateTimeField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    event_type = models.IntegerField(default=3)

    class Meta:
        db_table = "Event"

    @property
    def get_html_url(self):
        url = reverse('calendarSystem:event_edit', args=(self.event_id,))
        return f'<a href="{url}"> {self.title} </a>'

日程管理系统/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
	{% block bootsrap %}
            {% load bootstrap4 %}
 
            {# CSS Bootstrap #}
            {% bootstrap_css %} 
        {% endblock bootsrap %}
	<!-- basic -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- mobile metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<!-- site metas -->
	<title>{% block title %}BASE{% endblock %}</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="{% static 'images/favicon.ico' %}">
	<!-- bootstrap css -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<!-- style css -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- responsive-->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
	<!-- awesome fontfamily -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
	<style>
		.notif {
			float:right;
			margin-right: 5% ;
			text-align: center;
		}
	</style>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% block extracss %}

{% endblock extracss %}
</head>
<body class="main-layout">
	<div class="loader_bg">
		<div class="loader"><img src="{% static 'images/loading.gif' %}" alt="" /></div>
	</div>
	<header>
		<div class="header">
			<div class="container-fluid">
			<div class="row d_flex">
				<div class=" col-md-2 col-sm-3 col logo_section">
					<div class="full">
						<div class="center-desk">
						<div class="logo">
							<a href="/"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
						</div>
						</div>
					</div>
				</div>
				<div class="col-md-8 col-sm-9">
					<nav class="navigation navbar navbar-expand-md navbar-dark ">
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarsExample04">
						{% if user.is_authenticated %}
						<ul class="navbar-nav mr-auto">
							<li class="nav-item active">
								<a class="nav-link" href="/">Home</a>
							</li>
							
							<li class="nav-item">
								<a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'calendarSystem:calendar' %}">Calendar</a>
							</li>
						</ul>
						{% endif %}
						</div>
					</nav>
				</div>
				<div class="col-md-2 d_none">
					{% if user.is_authenticated %}
						<ul class="email text_align_right">
							<li> 
								<a href="{% url 'users:logout' %}">{{ user.username }}, Logout</a>
							</li>
						</ul>
					{% else %}
						<ul class="email text_align_right">
							<li> 
								<a href="{% url 'users:login' %}" >Login</a>
							</li>
						</ul>
					{% endif %}               
				</div>
			</div>
			</div>
		</div>
	</header>
	<br>
	<br>
	<br>
	<br>
	{% if user_form.errors %}
	<div class="alert alert-danger alert-dismissible" role="alert">
		<div id="form_errors">
		{% for key, value in user_form.errors.items %}
			<strong>{{ value }}</strong>
		{% endfor %}
		</div>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	{% endif %}
	<div class="notif" style="width: 90%;">
		{% if messages %}
			{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
					<h4>{{ message }}</h4>
				</div>
			{% endfor %}
		{% endif %}
	</div>
{% block content %}

{% endblock %}
	<!-- Javascript files-->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	</body>
</html>

日程管理系统/templates/calendar.html
{% extends 'base.html' %}
{% load static %}   

{% block title %}
Calendar
{% endblock %}

{% block extracss %}
    <style>
        body {
        font-family: "ptsans", "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        .left {
        float: left;
        }

        .right {
        float: right;
        }

        .btn {
        outline: none;
        color: black;
        background-color: transparent;
        box-shadow: 0 0 0 0;
        margin-right: 3px;
        }

        .clearfix {
        margin: 0px;
        }

        .form {
        margin: auto;
        }

        .form input, .form select, .form textarea {
        border-radius: 5px;
        border: 1px solid #17a2b8;
        outline: none;
        background: none;
        padding: 5px;
        width: 100%;
        }

        /* App styles */
        .title {
        text-align: center;
        margin: 10px;
        }

        .calendar {
        width: 98%;
        margin: auto;
        font-size: 13px;
        }

        .calendar tr, .calendar td {
        border: 1px solid black;
        }

        .calendar th {
        padding: 10px;
        text-align: center;
        font-size: 18px;
        }

        .calendar td {
        width: 200px;
        height: 150px;
        padding: 20px 0px 0px 5px;
        }

        .month {
        font-size: 25px;
        }

        .date {
        font-size: 16px;
        }

        ul {
        height: 100%;
        padding: 0px 5px 0px 20px;
        }

        a {
        color: #17a2b8;
        }
    </style>
{% endblock extracss %}

{% block content %}
    <div style="padding: 2em 0;">
        <br>
        <div class="clearfix"  >
            <a class="btn btn-info left" href="{% url 'calendarSystem:calendar' %}?{{ prev_month }}"> Previous Month </a>
            <a class="btn btn-info right" href="{% url 'calendarSystem:calendar' %}?{{ next_month }}"> Next Month </a>
            <a class="btn btn-info right" href="/cal/statistic/{{ thedate }}"> statistic </a>
            <a class="btn btn-info right" href="/cal/event/new/{{ dateval }}"> New Event </a>
        </div>
        <br>
        {{ calendar }}
    </div>
{% endblock %}

日程管理系统/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}   

{% block title %}
Home
{% endblock %}

{% block content %}
	<!-- start slider section -->
	<div id="top_section" class=" banner_main">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div id="myCarousel" class="carousel slide" data-ride="carousel">
						<div class="carousel-inner">
							<div class="carousel-item active">
								<div class="container-fluid">
									<div class="carousel-caption relative">
										<div class="bluid">
											<h1>Creative  <br>Calendar </h1>
											<p>There are many great day <br>that start by making organized calendar
											</p>
											<a class="read_more" href="{% url 'users:about' %}">About Beihang </a>
											<a class="read_more" href="{% url 'calendarSystem:calendar' %}">Calendar </a>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>         
				</div>
			</div>
		</div>
	</div>
	<footer>
		<div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
					<a class="logo_footer" href="#"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
					</div>
					<div class="col-md-9">
					<form action="/subscription/" class="newslatter_form" method="POST">
						{% csrf_token %}
						
						<input class="ente" placeholder="Enter your email" type="email" name="email">
						<button class="subs_btn">Subscribe Now</button>
					</form>
					</div>
					
				</div>
			</div>
			<div class="copyright text_align_left">
				<div class="container">
					<div class="row d_flex">
					<div class="col-md-6">
						<p>© 2023 Beihang University. </p>
					</div>
					<div class="col-md-6">
						<ul class="social_icon text_align_center">
							<li> <a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
							<li> <a href="Javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
							<li> <a href="Javascript:void(0)"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
							<li> <a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li> <a href="Javascript:void(0)"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
						</ul>
					</div>
					</div>
				</div>
			</div>
		</div>
	</footer> 
{% endblock %}

日程管理系统/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block extracss %}
	<style>
		.event{
			position: relative;
			margin-top: 30px;
			bottom: 0;
			left: 50px;
            width: 1000px;
		}
        fieldset {
            margin-bottom: 1em ;
            border: 1px solid #666 ;
            padding:1px !important;
        }

        legend {
            margin-left: 20px;
            padding: 10px 10px;
            float:none;
            width:auto;
        }
        .event-input {
            margin: 20px;
        }
	</style>
{% endblock extracss %}

{% block content %}
	<div class="event">
		<div class="clearfix">
			<a class="btn btn-info left" href="{% url 'calendarSystem:calendar' %}?{{ caldate }}"> Calendar </a>
		</div>
		<br>
	</div>	
	<center><h1>New Event</h1></center>
	<div class="event">
		<form method="post">
			<fieldset>
                <legend>Data Input:</legend>
				{% csrf_token %}
				<div class="event-input">
					<table class="form form-table">
						<tbody>
							<tr>
								<th>
									<label for="id_title">Title:</label>
								</th>
								<td>
									<input type="text" name="title" maxlength="200" required="" id="id_title">
								</td>
							</tr>
							<tr>
								<th>
									<label for="id_description">Description:</label>
								</th>
								<td>
									<textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
								</td>
							</tr>
							<tr>
								<th>
									<label for="event_type">Type:</label>
								</th>
								<td>		
									<select class="form-control" name="event_type" required>
										<option value="1">Lifestyle</option>
										<option value="2">Academic</option>
										<option value="3" selected>Not Specified</option>
									</select>					
								</td>
							</tr>
							<tr>
								<th>
									<label for="id_start_time">Start time:</label>
								</th>
								<td>
									<input type="datetime-local" name="start_time" required="" id="id_start_time" >
								</td>
							</tr>
							<tr>
								<td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>		
			</fieldset>
		</form>
	</div>
{% endblock %}

日程管理系统/templates/eventedit.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block extracss %}
	<style>
		.event{
			position: relative;
			margin-top: 30px;
			bottom: 0;
			left: 50px;
            width: 1000px;
		}

        fieldset {
            margin-left: 20px;
            margin-bottom: 1em ;
            border: 1px solid #666 ;
            padding:1px !important;
            width: 900px;
        }

        legend {
            margin-left: 20px;
            padding: 10px 10px;
            float:none;
            width:auto;
        }

        .event-input {
            margin: 20px;
        }
	</style>
{% endblock extracss %}

{% block content %}
    <div class="event">
		<div class="clearfix">
			<a class="btn btn-info left" href="{% url 'calendarSystem:calendar' %}?{{ date }}"> Calendar </a> 
		</div>
		<br>
	</div>	
    <center><h1>Edit Event</h1></center>
    <form method="POST" action="/cal/event/update/{{event.event_id}}">
        <fieldset>
            <legend>Data Input:</legend>
            {% csrf_token %}
            <div class="event-input">
                <table class="form form-table">
                    <tbody>
                        {% if flagadmin %}
                        <tr>
                            <th>
                                <label for="id_title">Title:</label>
                            </th>
                            <td>
                                <input type="text" name="title" maxlength="200" required="" id="id_title" value="{{event.title}}" readonly>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="id_description">Description:</label>
                            </th>
                            <td>
                                <textarea name="description" cols="40" rows="10" required="" id="id_description" readonly>{{event.description}}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="id_end_time">Event Type:</label>
                            </th>
                            <td>
                                <select class="form-control" name="event_type" required >
                                    <option value={{event.event_type}}>{{type}}</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="id_start_time">Start time:</label>
                            </th>
                            <td>{{event.start_time}}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button type="delete" class="btn btn-info right">
                                    <a href="{% url 'calendarSystem:calendar' %}?{{ date }}">Back</a>
                                </button>
                            </td>
                        </tr>
                        {% else %}
                        <tr>
                            <th>
                                <label for="id_title">Title:</label>
                            </th>
                            <td>
                                <input type="text" name="title" maxlength="200" required="" id="id_title" value="{{event.title}}">
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="id_description">Description:</label>
                            </th>
                            <td>
                                <textarea name="description" cols="40" rows="10" required="" id="id_description">{{event.description}}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="even_type">Event Type:</label>
                            </th>
                            <td>
                                {% if flagtype == 1 %}
                                    <select class="form-control" name="event_type" required>
                                        <option value={{event.event_type}}>{{type}}</option>
                                        <option value="2">Academic</option>
                                        <option value="3">Not Specified</option>
                                    </select>
                                {% elif flagtype == 2 %}
                                    <select class="form-control" name="event_type" required>
                                        <option value={{event.event_type}}>{{type}}</option>
                                        <option value="1">Lifestyle</option>
                                        <option value="3">Not Specified</option>
                                    </select>
                                {% elif flagtype == 3 %}
                                    <select class="form-control" name="event_type" required>
                                        <option value={{event.event_type}}>{{type}}</option>
                                        <option value="1">Lifestyle</option>
                                        <option value="2">Academic</option>
                                    </select>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <label for="id_start_time">Start time:</label>
                            </th>
                            <td>{{event.start_time}}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button type="submit" class="btn btn-info right" name = "update"> Submit</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <button type="submit" class="btn btn-info right", name = "delete">
                                    <a href="/cal/event/delete/{{event.event_id}}/">Delete</a>
                                </button>
                            </td>
                        </tr> 
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </fieldset>
    </form>
{% endblock %}

日程管理系统/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Sign In 
{% endblock %}

{% block extracss %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />  
{% endblock extracss %}

{% block content %}
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="wrap d-md-flex">
                        <div class="text-wrap p-4 p-lg-5 d-flex img" style="background-image: url('{% static 'images/bg.jpg' %}');">
                            <div class="text w-100">
                                <h2 class="mb-4">Welcome to Event Calendar System</h2>
                                <p>"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."</p>
                            </div>
                        </div>
                        <div class="login-wrap p-4 p-md-5">
                            <div class="row justify-content-center py-md-5">
                                <div class="col-lg-9">
                                    <div class="social-wrap">
                                        <h3 class="mb-3 text-center">Signin with this services</h3>
                                        <p class="social-media d-flex justify-content-center">
                                            <a href="#" class="social-icon google d-flex align-items-center justify-content-center"><span class="fa fa-google"></span></a>
                                            <a href="#" class="social-icon facebook d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
                                            <a href="#" class="social-icon twitter d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
                                        </p>
                                        <p class="or">
                                            <span>or</span>
                                        </p>
                                    </div>
                                    <form action="#" method="POST" class="signup-form">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="email">Username</label>
                                                    <input class="form-control placeholder-fix" type="text" placeholder="Username" name="username" required="">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="password">Password</label>
                                                    <input class="form-control placeholder-fix" type="password" placeholder="Password" name="password" required="" autocomplete="off">
        
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-primary">Sign In</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="w-100">
                                        <p class="mt-4">New in event calendar? <a href="/signup/">Sign Up</a></p>
                                        <p class="mt-4">I'm an admin! <a href="{% url 'users:signupadmin' %}" >Sign Up as an admin</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="{% static 'js/plugins/pace.min.js'%}"></script>
{% endblock %}

日程管理系统/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Profile Page
{% endblock title %}

{% block extracss %}
    
	<style>
		.profile{
			position: relative;
			bottom: 0;
			left: 50px;
            width: 1000px;
            z-index: 1;
		}

        fieldset {
            margin-bottom: 1em ;
            border: 1px solid #666 ;
            padding:1px ;
        }

        legend {
            margin-left: 20px;
            padding: 10px 10px;
            float:none;
            width:auto;
        }

        .bio-input {
            margin: 10px;
        }
	</style>
{% endblock extracss %}

{% block content %}
    <div class="profile">
        <div class="rowx my-3 p-3" style="max-width: 100%; max-height: 100%;">
            <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
        </div>
        {% if user_form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <div id="form_errors">
                    {% for key, value in user_form.errors.items %}
                        <strong>{{ value }}</strong>
                    {% endfor %}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}  
        <div class="form-content">
            <form method="post" enctype="multipart/form-data">    
            <fieldset>
                <legend>Bio Data</legend>
                    {% csrf_token %}
                    <div class="bio-input">
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="big mb-1">First Name:</label>
                                        {{ user_form.first_name }}
                                    <label class="big mb-1">Last Name:</label>
                                        {{ user_form.last_name }}
                                    <label class="big mb-1">Username:</label>
                                        {{ user_form.username }}
                                    <label class="big mb-1">Email:</label>
                                        {{ user_form.email }}
                                </div>
                                <div class="form-group">
                                    <hr>
                                    <label class="big mb-1">Change Profile Picture:</label>
                                    {{ profile_form.avatar }}
                                </div>
                            <label class="big mb-1" >Bio:</label> {{ profile_form.bio }}
                        </div>
                    </div>
                    <br>
                    <br>
                    </div>
                </fieldset>
                <a href="{% url 'users:change' %}"class="btn btn-dark btn-lg">Reset Password</a>
                <button type="reset" class="btn btn-dark btn-lg">Clear</button>
                <button type="submit" class="btn btn-dark btn-lg">Save</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>
{% endblock content %}

日程管理系统/templates/reset_notification.html
Dear {{ uname }},

We are writing to inform you that your password change request has been successfully processed and implemented in our system. This email serves as confirmation that your password has been updated for your account.

We understand the importance of maintaining the security and confidentiality of your account information, and we encourage regular password updates as part of our commitment to ensuring the safety of your data.

If you did not initiate this password change or believe it to be unauthorized, please contact our support team immediately at systemcalendar2023@gmail.com. We will investigate the matter promptly and take appropriate actions to safeguard your account.

To ensure the security of your account, we recommend following these best practices:

    Create a strong and unique password that includes a combination of uppercase and lowercase letters, numbers, and special characters.
    Avoid using easily guessable information such as birthdates, names, or common words.
    Regularly update your password and refrain from reusing it across multiple platforms.

Should you encounter any difficulties accessing your account or have any further inquiries, please do not hesitate to reach out to our support team. We are here to assist you.

Thank you for your attention to this matter. We appreciate your cooperation in maintaining a secure environment for our users.

Best regards,

Calendar System 2023